# Generated by Django 5.2 on 2025-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frontera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerimiento', models.CharField(max_length=100)),
                ('frontera', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('equipo_medida', models.CharField(max_length=100)),
                ('curva_tipica', models.CharField(max_length=100)),
                ('certificaciones', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
            ],
        ),
    ]
